// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-4ZW9WI-4-Tev186-yY6glcOdSDsUyi8',
    appId: '1:25695492653:web:d093f6ff13826120cb76a4',
    messagingSenderId: '25695492653',
    projectId: 'expense-tracker-e234c',
    authDomain: 'expense-tracker-e234c.firebaseapp.com',
    storageBucket: 'expense-tracker-e234c.firebasestorage.app',
    measurementId: 'G-ZMYS8EM2FF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJTlZkHbajnT40plgsjniGf9qK4eIaodQ',
    appId: '1:25695492653:android:26c9d887bb537558cb76a4',
    messagingSenderId: '25695492653',
    projectId: 'expense-tracker-e234c',
    storageBucket: 'expense-tracker-e234c.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhBUl-kC9E_VG2oeXAaovf4fcxKS9kJdw',
    appId: '1:25695492653:ios:399f98a6593abb7fcb76a4',
    messagingSenderId: '25695492653',
    projectId: 'expense-tracker-e234c',
    storageBucket: 'expense-tracker-e234c.firebasestorage.app',
    iosBundleId: 'com.example.pulsespend',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhBUl-kC9E_VG2oeXAaovf4fcxKS9kJdw',
    appId: '1:25695492653:ios:399f98a6593abb7fcb76a4',
    messagingSenderId: '25695492653',
    projectId: 'expense-tracker-e234c',
    storageBucket: 'expense-tracker-e234c.firebasestorage.app',
    iosBundleId: 'com.example.pulsespend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-4ZW9WI-4-Tev186-yY6glcOdSDsUyi8',
    appId: '1:25695492653:web:c0ffb83b2a7e74b0cb76a4',
    messagingSenderId: '25695492653',
    projectId: 'expense-tracker-e234c',
    authDomain: 'expense-tracker-e234c.firebaseapp.com',
    storageBucket: 'expense-tracker-e234c.firebasestorage.app',
    measurementId: 'G-K2LHGG4ZQZ',
  );
}
